
---

- name: Upgrade Linux
  hosts: all
  become: yes

  tasks:
  - name: Check and Print Linux Version
    debug:
     var: ansible_os_family

  - block: #Блок для RedHat

    - name: Upgrade all packages RedHat
      ansible.builtin.yum:
        name: '*'
        state: latest

    when: ansible_os_family == "RedHat"

  - block: #Блок для Debian

#    - name: Run the equivalent of "apt-get update" as a separate step
#      ansible.builtin.apt:
#        update_cache: yes

#    - name: Upgrade the OS (apt-get dist-upgrade)
#      ansible.builtin.apt:
#          upgrade: dist

    - name: Update all packages Debian
      ansible.builtin.apt:
        name: "*"
        state: latest

    when: ansible_os_family == "Debian"

...

