
---

- name: Install Apache and Upload Web Page
  hosts: all
  become: yes

  vars:
    source_file: ./MyWebSite/index.html
    destin_file: /var/www/html

  tasks:
  - name: Check and Print Linux Version
    debug:
     var: ansible_os_family

  - block: #Блок для RedHat

    - name: Install Apache Web Server
      yum: name=httpd state=installed

    - name: Copy MyHomePage to Servers
      copy: src={{ source_file }} dest={{ destin_file }} mode=0555
      notify: Restart Apache RedHat

    - name: Start Apache and Enable
      service: name=httpd state=started enabled=yes

    when: ansible_os_family == "RedHat"

  - block: #Блок для Debian

    - name: Install Apache Web Server
      apt: name=apache2 state=present

    - name: Copy MyHomePage to Servers
      copy: src={{ source_file }} dest={{ destin_file }} mode=0555
      notify: Restart Apache Debian

    - name: Start Apache and Enable
      service: name=apache2 state=started enabled=yes

    when: ansible_os_family == "Debian"

  handlers:
  - name: Restart Apache RedHat
    service: name=httpd state=restarted

  - name: Restart Apache Debian
    service: name=apache2 state=restarted

...

