
---
- name: Ansible Lesson 19
  hosts: all
  any_errors_fatal: true
  become: yes

  tasks:
  - name: Task Number 0
    yum: name=tree state=latest
    ignore_errors: yes

  - name: Task Number 1
    apt: name=tree state=latest
    ignore_errors: yes

  - name: Task Number 2
    shell: echo Hello World!
    register: results
#    failed_when: results.rc == 0

  - debug:
      var: results

  - name: Task Number 3
    shell: echo Privet Mir!!!
