---
- name: Create AWS EC2 Instance
  hosts: local
  connection: local
  gather_facts: false
  vars:
    keypair: evgen-key-n_virginia                       # Name of KeyPain as written in AWS Console
    instance_type: t2.micro                                   # Type of EC2 Server to Create
    image: ami-0df435f331839b2d6                      # AMI of Server in This Region
    region: us-east-1                                  # Name of Region
    count: 4                                          # How many Servers to Create
    security_group: HTTP-HTTPS-SSH-RDP                      # Name for SecurityGroup
    aws_access_key: AKIA...                      # Credentials to Create AWS EC2
    aws_secret_key: 0EZrVe...                    # Credentials to Create AWS EC2

  tasks:
    - name: Create a security group with Port 22 and 80 Open to 0.0.0.0/0
      ec2_group:
        name: "{{ security_group }}"
        description: Security Group for Servers with port 22,80,443 Open
        region: "{{ region }}"
        rules:
          - proto: tcp
            from_port: 22
            to_port: 22
            cidr_ip: 0.0.0.0/0
          - proto: tcp
            from_port: 80
            to_port: 80
            cidr_ip: 0.0.0.0/0
          - proto: tcp
            from_port: 443
            to_port: 443
            cidr_ip: 0.0.0.0/0
        rules_egress:
          - proto: all
            cidr_ip: 0.0.0.0/0
            aws_access_key: "{{ aws_access_key }}"
            aws_secret_key: "{{ aws_secret_key }}"

    - name: Create New AWS EC2 Server
      ec2:
        key_name: "{{ keypair }}"
        instance_type: "{{ instance_type }}"
        image: "{{ image }}"
        group: "{{ security_group }}"
        region: "{{ region }}"
        instance_tags:
            Name: Ansible Deployment
            Type: Ansible EC2-IT
        count: "{{ count }}"
        wait: true
        aws_access_key: "{{ aws_access_key }}"
        aws_secret_key: "{{ aws_secret_key }}"
      register: ec2             # Start Creation of AWS EC2 Server

    - name: Print all ec2 variables
      debug: var=ec2
